### ISSUE TITLE
Aangeboden hoeveelheid producten wordt overschreden tijdens bestellen

### ISSUE THREAD

**Issue by peteruithoven** [VOKO-Utrecht/voko#119]
Het aangeboden hoeveelheid producten wordt overschreden tijdens bestellen?

> Goede avond,
>
> Dank voor de bestelling. Ik hoop dat het gaat lukken met de
> hoeveelheden. Van een aantal producten die besteld zijn heb ik minder
> aangeboden dan dat jullie bestellen. Dat is niet de eerste keer dat
> dit gebeurt. Zouden jullie daar op willen letten? Bijvoorbeeld de
> tuinbonen, max 10 geef ik aan. En nu is er 11 x besteld, de doperwten
> ook max 6 Ingevuld en 7 besteld.
> Dat is toch bijzonder. Hebben jullie enig idee hoe dat kan en in het
> vervolg voorkomen kan worden?
>
> Hartelijke groet,
>
> x
> Food for good
> Stichting de Wending

**Comment by rikva** [comment]
Oeps...


Op do jun 11 2020, om 0:12 schreef Peter Uithoven:

**Comment by rikva** [comment]
Als ik het zo zie lijkt het op een off-by-1 bug

**Comment by mgvd** [comment]
In FinishOrder wordt gecontroleerd of de producten nog beschikbaar zijn. Echter, als men gaat betalen, met FinishOrder-post, wordt dit niet meer gecheckt. Als we daar de check toevoegen is het nog niet waterdicht. Het kan zijn dat iemand gaat betalen en dat een ander lid op dat moment zijn betaling nog niet heeft afgerond (zoeken naar de identifier). Door groeiend aantal leden wordt de kans groter dat dit voorkomt. 
Als we een status aan de order toevoegen 'is_paying', dan kunnen we de aantal van die orders meenemen als we controleren of een product beschikbaar is. De producten zijn de als het ware 'gereserveerd'. Als de betaling wordt afgebroken moet de order van 'is_paying' af en zijn de producten weer beschikbaar.

**Comment by mgvd** [comment]
Fix suggested but similar issues have not been reported. Number of orders is stable. Close for now
