### ISSUE TITLE
Improve user list for Rides

### ISSUE THREAD

**Issue by mgvd** [VOKO-Utrecht/voko#207]
The users lists are quite large, if not to hard I'd love to add some kind of search / filter functionality. Ideally for the driver and codriver a dropdown with a filter.

**Comment by bveldkamp** [comment]
Is this about /transport/members/ ? It wouldn't be hard to implement a generic client side filter with a single text input, where each TD is checked for matching text, and the TR's visibility is set accordingly. Or are you looking for more advanced filter functionality?

**Comment by bveldkamp** [comment]
Well, that was easy. 
One detail though: By default, the autocomplete searches in all user fields. In this case, it makes sense to search in first and last name only, and not e.g. e-mail. Specific search fields can be set on VokoUserAdmin, but this also influences the search functionality on the /admin/accounts/vokouser page, where searching on e-mail might be helpful.
