### ISSUE TITLE
Saldo van geanonimiseerde leden

### ISSUE THREAD

**Issue by Jazzper80** [VOKO-Utrecht/voko#356]
Verzoek vanuit finance om het saldo van geanonimiseerde leden te verwijderen i.v.m. het kloppend maken van de boekhouding.

**Comment by bveldkamp** [comment]
Eigenlijk zou iemand van finance een extra debit balans moeten toevoegen voor die users, alleen staan de anonieme accounts zo te zien in niet in die lijst, dus dat gaat niet lukken. Ik geloof dat het om ~20 gevallen gaat, dus de pragmatische oplossing is dat ik dat handmatig in de database aanpas. Ik ben nog bezig met #343 waardoor dit in de toekomst sws niet meer kan gebeuren.

@Jazzper80 Weet jij of onze provider ergens een optie heeft om de database rechtstreeks te benaderen, via een web-interface of zo?

**Comment by mgvd** [comment]
Ik heb Berend rechtstreeks gemaild met info over verbindingen met de DB


Op di 16 jul 2024 om 19:47 schreef Berend Veldkamp ***@***.***

**Comment by bveldkamp** [comment]
Getest op acceptatie omgeving, ik zal productie aanpassen zodra de huidige bestelronde klaar is (zou niet uit moeten maken voor slapende leden, maar just in case)

**Comment by bveldkamp** [comment]
Saldo van 22 anonieme leden is gecorrigeerd en staat nu op 0 euro
