### ISSUE TITLE
Leden uit de Financien groep kunnen niet bij het besteloverzicht

### ISSUE THREAD

**Issue by bveldkamp** [VOKO-Utrecht/voko#361]
Voorheen waren alle financiele leden ook admin, maar omdat dat nu is teruggedraaid kunnen ze niet meer bij het besteloverzicht, dwz /ordering/admin/rounds/

In webapp/ordering/admin_views.py de groep rechten geven op deze pagina

**Comment by bveldkamp** [comment]
@Jazzper80 Vraagje: moeten financiële leden in het besteloverzicht ook kunnen doorklikken naar Bestellijsten voor leveranciers, Unieke bestellingen, Overzicht bestellingen per product en Correcties? 

![image](https://github.com/user-attachments/assets/ce099cf6-b116-4ba6-ae5a-4b0026244d9a)

**Comment by Jazzper80** [comment]
@bveldkamp Dat hadden ze eerder wel, dus dat vinden ze fijn om te hebben. Is blijkbaar vaak niet nodig, maar 'just in case'.

**Comment by Jazzper80** [comment]
Hoi Berend, 

Luuk kan nog steeds niet bij het besteloverzicht. Hij gebruikt de volgende link: [https://leden.vokoutrecht.nl/ordering/admin/rounds/ ](url). Enig idee waaro dit is?

**Comment by Jazzper80** [comment]
Ah ok vandaar. Als het vanavond zou kunnen zou dat fijn zijn, omdat finance nu niet hun checks kunnen doen en de facturen afhandelen.
