### ISSUE TITLE
Inline register form

### ISSUE THREAD

**Issue by peteruithoven** [VOKO-Utrecht/voko#52]
Currently on our public vokoutrecht website we have added an image that links to the registration form:
https://vokoutrecht.nl/meedoen/

UX wise I'd like to move this form to vokoutrecht.nl, but this requires sending a post request to leden.vokoutrecht.nl. But seeing that hidden `csrfmiddlewaretoken` in the registration form I'm afraid that won't be easy. 
Right?

I'd like to see the form at least inlined, using an iframe.

**Comment by peteruithoven** [comment]
Inlining it using a iframe doesn't currently work though. 
Looks like that's caused by a [`X-Frame-Options` HTTP response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) that's set to `SAMEORIGIN`
Ideally that would be set to: `allow-from https://vokoutrecht.nl/`

As far as I understand this it looks like it requires configuration of the webserver. Some examples:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options?utm_source=mozilla&utm_medium=devtools-netmonitor&utm_campaign=default#Examples

@rikva could you help with this?

**Comment by peteruithoven** [comment]
@rikva do you have any thoughts on this?

**Comment by rikva** [comment]
I don't think we want to mess with the SAMEORIGIN headers. We could remove the CSRF protection from the register form, so you can replicate the form on the website and post the data directly to the python system. Is that an option?

**Comment by peteruithoven** [comment]
Yeah that would be an option. It will take a bit more effort but having the form on the site itself including style sounds like a good idea.

**Comment by mgvd** [comment]
Won´t do
