### ISSUE TITLE
Handle 1 member who uses multiple accounts

### ISSUE THREAD

**Issue by peteruithoven** [VOKO-Utrecht/voko#62]
For the VOKO a active member is an account that has payed at least one order, which also means they payed their contribution. 

We have a few couples where we partly see them as one member, they payed one contribution, frequently one of them contributes, but they have 2 accounts. 

This means one of them payed the contribution and performs orders, meaning we see this account as a real member, but we don't really see the other account as a valid member. 

How could we properly handle this? Without asking people to pay the contribution twice?

**Comment by mgvd** [comment]
Won´t do for now. This has come up in other discussion, but not frequently. Suggestion to use one account, and enter name as "Klaas en Jenny" if they share the participation.
