### ISSUE TITLE
Meer leden correcties laten doorvoeren?

### ISSUE THREAD

**Issue by peteruithoven** [VOKO-Utrecht/voko#97]
Bij de afgelopen ALV werdt duidelijk dat 1 van de irritante taken van uitdeel coördinators is dat de correcties doorgegeven moeten worden. We willen daarom proberen of de personen die de late dienst doen dit misschien kunnen overnemen. 

- Is dat mogelijk?
- Wat voor rechten komen daarbij kijken? 
- Is het handig om daarvoor een correctionsteam / distributionAdmin / ... rol te maken ?

**Comment by mgvd** [comment]
Seems not be a big problem, never mentioned since over two years
